# Generated by Django 6.0.1 on 2026-01-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0003_demanda_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_previsao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='justificativa_pendencia',
            field=models.TextField(blank=True),
        ),
    ]
