# Generated by Django 6.0.1 on 2026-01-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0004_demanda_data_previsao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='justificativa_pendencia',
            new_name='motivo_atraso',
        ),
        migrations.RenameField(
            model_name='demanda',
            old_name='data_previsao',
            new_name='nova_data',
        ),
    ]
