# Generated by Django 6.0.1 on 2026-01-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0005_rename_justificativa_pendencia_demanda_motivo_atraso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='demanda_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_geradas', to='unanime.demanda'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberto'), ('CO', 'Concluído'), ('PE', 'Pendente'), ('FE', 'Fechado')], default='AB', max_length=2),
        ),
    ]
