# Generated by Django 6.0.1 on 2026-01-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0006_demanda_demanda_origem_alter_demanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='demanda_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagendamentos', to='unanime.demanda'),
        ),
    ]
