# Generated by Django 6.0.1 on 2026-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0007_alter_demanda_demanda_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
