# Generated by Django 6.0.1 on 2026-02-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0009_demanda_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unanime.titulodemanda'),
        ),
    ]
