# Generated by Django 6.0.1 on 2026-02-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unanime', '0010_titulodemanda_alter_demanda_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
